### ISSUE TITLE
Is this supported by the nginx itself?

### ISSUE THREAD

**Issue by abhisheksurve45** [wandenberg/nginx-sorted-querystring-module#6]
Was wondering since this is a 7 year old repository, has nginx already added a support to sort query parameters in some way?

**Comment by abhisheksurve45** [comment]
Is there any other way apart from `lua`?

**Comment by se2342** [comment]
AFAIK with Nginx there is no out-of-the-box way to achieve what you want. That's why @wandenberg created this helpful module.

Have a look at OpenResty or https://nginx.org/en/support.html if you don't want to use this module (which even 7 years later still works fine, by the way).

**Comment by abhisheksurve45** [comment]
Thank you @se2342 for your suggestion, will try out this module.
